spring.application.name=guesthouse-customer-service

server.port=8081
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.datasource.url=jdbc:mysql://guesthouse-customer-service:3306/guesthouse-db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
